cleaner dependencies install

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,10 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Install Dependencies
-        run: opam install -y odoc menhir $(dune external-lib-deps @all | sed -n 's|- \(.*\)\..*|\1|p')
+        run: dune build 2>/dev/null || true; opam install -y menhir; opam install -y . --deps-only --with-doc --with-test
+        ## FIXME: this line is a bit twisted because of two bugs:
+        ## - The explicit installation of Menhir is here to mitigate #4486.
+        ## - The caught failure (; instead of &&) of dune build is here to mitigate #4487.
 
       - name: Try Building
         run: make build
